#!/bin/bash
#$ -cwd
#$ -N log_time
#$ -l cuda=1
#$ -l mem=4G
#$ -l nv_mem_free=9G
#$ -l hostname=*vector*
#$ -l h_rt=00:51:00
#$ -o /dev/null"
#$ -m n
#$ -pe default 1


echo " Start of SGE job "
echo "$date"
# Identify Job-ID
echo ""
echo "Hostname"
echo "$HOSTNAME"
echo 'Job-ID:'
echo $JOB_ID
echo 'user:'
echo $USER
echo ""
echo "Start"
echo ""

setup_file=code/grid_time_test.py
env_name=torch
#Scratch_wd_21 is a variable that stores the path to my scratch folder in which i installed anaconda
export SCRATCH_WD_21="/net/projects/scratch/summer/valid_until_31_January_2021/sgroen"
# create the pythonpath variable based on the location of where my anaconda is installed
export PYTHONPATH=$SCRATCH_WD_21:$PYTHONPATH
# activate my environment
source $SCRATCH_WD_21/miniconda/bin/activate $env_name

echo "RUNNING: " $setup_file
echo "Current Environemt: " $env_name


python $setup_file

